### ISSUE TITLE
This is a very meaningful paper， I want to know when it will be open source

### ISSUE THREAD

**Issue by chenyuanpengcyp** [hustvl/LaneGAP#1]
This is a very meaningful paper I want to know when it will be open source.

**Comment by LegendBC** [comment]
Thanks for your appreciation. But sorry that I can only upload the code after the LaneGAP is accepted. But I promise to release the code as my previous works , please stay tuned to this repo.

**Comment by Jiayiiiiiii502** [comment]
> 
Wondering if this model is accepted now？

**Comment by outsidercsy** [comment]
Code of LaneGAP is released together with MapTRv2 (https://github.com/hustvl/MapTR).

**Comment by Jiayiiiiiii502** [comment]
thanks！

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
