### ISSUE TITLE
Truly Solid Research. Hope to See Codes Soon!

### ISSUE THREAD

**Issue by ZhangGongjie** [hustvl/LaneGAP#3]
Hi authors, you have done some really solid research! You have my respect! 

A gentle inquiry: when can I expect your codes to be released? I am really looking forward to trying it!

**Comment by LegendBC** [comment]
Thanks for your appreciation! Due to the regulation of the cooperative company,  I can only upload the code after the LaneGAP is accepted, please stay tuned to this project. Thanks again for your appreciation!
